apiVersion: v1
kind: ConfigMap
metadata:
  name: mitmproxy-config
  labels:
    {{- include "mitmproxy.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- .Files.Get "config.yaml" | nindent 4 }}
